### ISSUE TITLE
Add link in the top menu to the speakers page 

### ISSUE THREAD

**Issue by mjzac** [startupchile/startupchile.github.io#10]
Links should be given in the top menu to `speakers` page and other relevant pages.

**Comment by diegomorales85** [comment]
Thanks! WHo's in charge of uploading this? I think we're doing the agenda
as we speak..

On Thu, Aug 20, 2015 at 1:56 PM, Melson J Zacharias <
notifications@github.com> wrote:

> Links should be given in the top menu to speakers page and other relevant
> pages.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/startupchile/startupchile.github.io/issues/10.

## 

Diego Morales | Director of Marketing

[image: 5eN9waH.png]

startupchile.org http://www.startupchile.org/

@startupchile https://twitter.com/startupchile / @diegomorales85
https://twitter.com/diegomorales85

LinkedIn https://www.linkedin.com/pub/diego-morales/48/4a3/393

**Comment by mjzac** [comment]
Link to speaker page has been added to the navbar.
