### ISSUE TITLE
Create attendees/ event data section in home page

### ISSUE THREAD

**Issue by mjzac** [startupchile/startupchile.github.io#18]
add the attendees / event data section in home page as in http://gdg-x.github.io/zeppelin/

**Comment by mjzac** [comment]
Statistics section has been integrated to home page.

**Comment by diegomorales85** [comment]
Thanks! But the state hace to be real!!!

On Wednesday, August 26, 2015, Melson J Zacharias notifications@github.com
wrote:

> Statistics section has been integrated to home page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/startupchile/startupchile.github.io/issues/18#issuecomment-135193523
> .

## 

Sent from Gmail Mobile
